POST  http://localhost:3000/user
Content-Type: application/json

{
    "email":"marcisa@gmail.com",
    "name":"name",
    "role":"role",
    "password":"password",
    "salt":"salt",
    "confirmationToken":"confirmationToken",
    "recoverToken":"recoverToken",
    "createdAt":null,
    "updatedAt":null
}
###

Get  http://localhost:3000/user